### ISSUE TITLE
Dragging a new event doesn't register the drag start position correctly

### ISSUE THREAD

**Issue by g105b** [nibdo/bloben-app#10]
Hey - I'm impressed by this project. Saw it on HN, thanks for sharing! I played around for a while and found a minor bug that I thought I'd share.

From the main week view, I expect to be able to click and drag the length of a new event. It works if I'm very slow, but if I click and drag the event at normal operating speed with the mouse, the start position of the event is missed. There seems to be ~100ms delay between my actual click start, and when the new event's position is registered.

Hope this makes sense, take care!

EDIT: Should have added, Windows 10 Edge v 100.0.1185.29

**Comment by nibdo** [comment]
Should be improved in 0.6.1

**Comment by g105b** [comment]
Yeah, it's nice and responsive now :)
