### ISSUE TITLE
Sync with malformed event not working

### ISSUE THREAD

**Issue by bam91** [nibdo/bloben-app#11]
Hey,

first: very great Project!

I have installed bloben on my unraid and currently syncing against three different Nextcloud-instances. Two of them are working fine, but at one instance i cannot get any Calendars or appointments.
After adding the account do bloben i am getting the following error in my logs:
`{"level":"error","message":"Sync caldav events error: Date is not valid - Error: Date is not valid\n    at validateISOStringDate (/usr/app/api/node_modules/ical-js-parser/toJSON/validator.js:9:15)\n    at formatToIsoDate (/usr/app/api/node_modules/ical-js-parser/toJSON/dateHelpers.js:19:43)\n    at parseICalDate (/usr/app/api/node_modules/ical-js-parser/toJSON/dateHelpers.js:37:53)\n    at splitRowToKeyValueObj (/usr/app/api/node_modules/ical-js-parser/toJSON/index.js:141:49)\n    at formatStringToKeyValueObj (/usr/app/api/node_modules/ical-js-parser/toJSON/index.js:65:24)\n    at getResult (/usr/app/api/node_modules/ical-js-parser/toJSON/index.js:85:43)\n    at getOneEventJSON (/usr/app/api/node_modules/ical-js-parser/toJSON/index.js:99:12)\n    at /usr/app/api/node_modules/ical-js-parser/toJSON/index.js:220:16\n    at Array.map (<anonymous>)\n    at Object.toJSON (/usr/app/api/node_modules/ical-js-parser/toJSON/index.js:219:31)","tags":["REST","CALDAV"],"timestamp":"2022-04-08 09:35:58"}`

I think there is maybe a maleformed appointment in my calendar which is generating this exception. Is there any possibiliy to use some kind of try/catch to get the appointments?

Kinds
bam91

**Comment by nibdo** [comment]
Hello, thank you for reporting this. I will adjust it and add better logs for problems like this. I will let you know.

**Comment by nibdo** [comment]
Hi, you can check new version 0.5.1 where this should be handled better. Also you should now see that problematic date in the logs. If you could find it, I will check what was causing this. Thank you

**Comment by Joshndroid** [comment]
@bam91 I am unable to email you directly but would you care to share your unraid template (minus your session secret and OTP secret  and any other personal info of course)...

**Comment by bam91** [comment]
> Hi, you can check new version 0.5.1 where this should be handled better. Also you should now see that problematic date in the logs. If you could find it, I will check what was causing this. Thank you

I have updated to your latest version. It is now working like a charm. Currently there are no errors in the logs. If I can spot one I will inform you. Thank you for your support

**Comment by Joshndroid** [comment]
@bam91 I am unable to email you directly but would you care to share your unraid template (minus your session secret and OTP secret and any other personal info of course)...

**Comment by bam91** [comment]
@Joshndroid I did not use a template for this. I am currently using the docker-compose plugin of unraid with the example provided by @nibdo . 

I did this because I wanted to quickly test this project and didn't know which env-variables belong to the single containers.

**Comment by Joshndroid** [comment]
Thanks for your response..
I have a long list of env vars in my template and something is not playing nice at present, sadly :(
Cheers again
