### ISSUE TITLE
user not login page where use not logged

### ISSUE THREAD

**Issue by yanickxia** [nibdo/bloben-app#17]
app version: 6.0.0
`/admin` show login page, but `/calendar` not show login page. fallback to 0.5.2 working

**Comment by nibdo** [comment]
Hello, could you please check if any elements were rendered? And maybe try clearing cache or different browser? 

Demo site is on 6.0.0 and can't see anything strange in this case :/ 

![login](https://user-images.githubusercontent.com/57879411/164318981-f0518b0d-b824-4a1e-870e-f13ec9b833fe.png)
