### ISSUE TITLE
Redis ENV variables?

### ISSUE THREAD

**Issue by Joshndroid** [nibdo/bloben-app#20]
Hello,
I am trying to get this running on unraid.
I already have a redis docker container and have managed to get the post gres stuff working...
I am sitting in the logs with 

`ReplyError: NOAUTH Authentication required.
at parseError (/usr/app/api/node_modules/redis-parser/lib/parser.js:179:12)
at parseType (/usr/app/api/node_modules/redis-parser/lib/parser.js:302:14) {
command: { name: 'info', args: [] }'

with basically;

Error: Connection is closed.

I have tried ENV vars REDIS_PASSWORD, REDIS_USERNAME, REDIS_DATABASE but none of these seem to play nice.

**Comment by Joshndroid** [comment]
I also tried to use a fresh redis container and got the same error

**Comment by nibdo** [comment]
Hi @Joshndroid, if I understand this correctly, you want to use some other Redis container which you already have and it is password protected? 

Currently Bloben server app doesn't use authentication for Redis, so that could be this issue. But it won't be problem to add for your use case.

**Comment by Joshndroid** [comment]
Hey mate,
Thanks for the reply.
Yep each container I have for redis has a password and database name.
What variables should I be using to pass it through?

**Comment by Joshndroid** [comment]
I have currently redeployed my redis and changed my other containers in order to get this one further. I still would like to see if there are any further additions that can assist in getting password/database name support going forward

**Comment by nibdo** [comment]
@Joshndroid I have added option to connect with ENV REDIS_URL like this:

`REDIS_URL=redis://user:password@host:port/db`

You might need to check if that user has correct permissions for commands which are required by redis library used in server. Hope this will work for you.

Version 0.7.1

**Comment by Joshndroid** [comment]
@nibdo thanks for the swift update.
I have a separate issue at present so ill close this one now its sorted

**Comment by shotcowboystyle** [comment]
> @Joshndroid I have added option to connect with ENV REDIS_URL like this:
> 
> `REDIS_URL=redis://user:password@host:port/db`
> 
> You might need to check if that user has correct permissions for commands which are required by redis library used in server. Hope this will work for you.
> 
> Version 0.7.1

@nibdo First thanks for the great app!!!

Just wanted to point out that this looks to have been reverted here: https://github.com/nibdo/bloben-api/commit/45bf4fbcff6483ed242fdac22976d840826309c3#diff-c4dcde3103bae450b1a9a277932abcbd60151c6bc9078eb5c9b574f612370768

Was this intentional?

**Comment by nibdo** [comment]
@shotcowboystyle no, it was probably forgotten during refactoring. Thank you.

I have published fix in 0.17.3

**Comment by shotcowboystyle** [comment]
Awesome and again thank you for the product 😄 !!!

**Comment by shotcowboystyle** [comment]
@nibdo I'm using an existing Redis cluster that uses Redis Sentinel and is password protected. So I need to pass in a Redis Sentinel connection object, ie:

```
{
  "sentinels": [
    {
      "host": "sentinel-0",
      "port":26379
    }, {
      "host":"sentinel-1",
      "port":26379
    }
  ],
  "name":"mymaster",
  "password": "mypassword"
}
```

I've created a PR that should allow the original functionality (using env vars - `REDIS_HOST` and `REDIS_PORT`), as  well as the above mentioned functionality using a string (`REDIS_URL=redis://user:password@host:port/db`) as well as the ability to pass in my connection object as a base64 encoded string (`REDIS_URL=ioredis://eyJzZW50aW5lbHMiOlt7Imhvc3QiOiJzZW50aW5lbC0wIiwicG9ydCI6MjYzNzl9LHsiaG9zdCI6InNlbnRpbmVsLTEiLCJwb3J0IjoyNjM3OX1dLCJuYW1lIjoibXltYXN0ZXIifQ==`) however, the only check it currently handles is assuming that the `REDIS_URL` holding an encoded connection object starts with `ioredis://` vs `redis://`, which can be better handled with either an additional env var or or at the very least a bit of clarity in the documentation.

PR: [https://github.com/nibdo/bloben-api/pull/224](https://github.com/nibdo/bloben-api/pull/224)

**Comment by nibdo** [comment]
@shotcowboystyle thank you for contribution. I have merged and released it.
