### ISSUE TITLE
Modify apiUrl to match host

### ISSUE THREAD

**Issue by pchampio** [nibdo/bloben-app#22]
The apiUrl is hardcoded on line: https://github.com/nibdo/bloben-calendar/blob/a759bc288de6b2e7fc9fc3a003431bab2a4631aa/src/layers/AuthProvider.tsx#L24-L26
I'll like to use this feature to easily share my calendar in read-only with anyone.

BTW, it is a fantastic project. I'm thrilled to have a nice-looking web calendar application. :+1:

**Comment by nibdo** [comment]
Hi @pchampio, thank you, I will check that demo redirect.

About calling request for version, this was intention for checking new updates directly from the app. I have it actually in backlog how to approach those notifications. Basically there are more or less three options:

1. User will have to check versions manually.
2. Checking either published version on Github or my published version at bloben.com
3. Combined point 1 and 2 with option to turn on/off checking from admin dashboard.

**Comment by nibdo** [comment]
Those issues should be resolved in new version 0.7.2

Version checking is now optional settings from admin dashboard.
