### ISSUE TITLE
[Feature] Search

### ISSUE THREAD

**Issue by pchampio** [nibdo/bloben-app#24]
I'll love to have the ability to search events.

**Comment by nibdo** [comment]
Added basic search in 0.10.0

More advanced filters might come later.

**Comment by pchampio** [comment]
Awesome!
Currently the search feature is only available for non-demo users.
I think I should be available for demo user as it is a read-only operation.

**Comment by nibdo** [comment]
Thanks for comments. Yes, it could be made for demo users too, I will just have to add some limitations. Probably rate limiter as it might be little bit heavy for server, if random people would be spamming it as it it is real time search.

I have added some ordering, but it might be not working good, so I will check it.
