### ISSUE TITLE
Vertical line disapering

### ISSUE THREAD

**Issue by pchampio** [nibdo/bloben-app#25]
https://user-images.githubusercontent.com/7476655/168447261-60af89bc-49db-4c9a-af15-050aa5451fb6.mp4

Modifying the line width to `0.5` fixes the issue.
Using firefox.

**Comment by nibdo** [comment]
Thank you. I had to bump it to 1px, because it was still acting little bit strange.

Fix will be in next release.

**Comment by nibdo** [comment]
Fixed in 0.8.0
