### ISSUE TITLE
New lines are not displayed

### ISSUE THREAD

**Issue by albsch** [nibdo/bloben-app#32]
New lines are shown literally.

Agenda:

![image](https://user-images.githubusercontent.com/38429047/170635946-3c02d812-7664-4790-bf10-883a1c989bbe.png)

Day:
![image](https://user-images.githubusercontent.com/38429047/170636147-3be2e0ec-4ffe-4315-b1ce-b3c7737f80f3.png)

**Comment by albsch** [comment]
Commas are also escaped in the raw files and are displayed in the calendar `\,`.

**Comment by nibdo** [comment]
Hi @albsch, is this and https://github.com/nibdo/bloben-app/issues/31 issue still presented in new version 0.15.2? Thanks

**Comment by albsch** [comment]
Fixed, thanks!
