### ISSUE TITLE
Syncing with DavMail

### ISSUE THREAD

**Issue by albsch** [nibdo/bloben-app#36]
I would like to get my last missing calendars to work. Right now, the account was added successfully, the calendars are discovered and displayed on the left side. But no events are loaded. There are also no log messages indicating errors. On my davmail logs, this is logged, indicating some communication issue:

```
davmail-work-exchange-davmail-work-1  | 2022-05-27 05:54:52,743 ERROR [CaldavConnection-33232] davmail  - Invalid Caldav request: Unexpected EOF in prolog
davmail-work-exchange-davmail-work-1  |  at [row,col {unknown-source}]: [1,0]
davmail-work-exchange-davmail-work-1  | davmail.exception.DavMailException: Invalid Caldav request: Unexpected EOF in prolog
davmail-work-exchange-davmail-work-1  |  at [row,col {unknown-source}]: [1,0]
davmail-work-exchange-davmail-work-1  |         at davmail.caldav.CaldavConnection$CaldavRequest.parseXmlBody(CaldavConnection.java:1590)
davmail-work-exchange-davmail-work-1  |         at davmail.caldav.CaldavConnection$CaldavRequest.<init>(CaldavConnection.java:1395)
davmail-work-exchange-davmail-work-1  |         at davmail.caldav.CaldavConnection.handleRequest(CaldavConnection.java:224)
davmail-work-exchange-davmail-work-1  |         at davmail.caldav.CaldavConnection.run(CaldavConnection.java:180)
```

Any idea why no error is logged and what could be done to debug this issue further?

Also, at some point, the calendar starts duplicating itself:

![image](https://user-images.githubusercontent.com/38429047/170640212-718bcacf-0847-44f6-9794-b695f27dde20.png)

**Comment by nibdo** [comment]
There is some incompatibility probably with used CalDAV library in bloben and server (with xml body). I have found some similar problems from other people, but I think I would need to run some testing server to debug this better.

**Comment by nibdo** [comment]
Hi @albsch, is this please still relevant, or can I close it?

**Comment by albsch** [comment]
It's not that relevant anymore.
