### ISSUE TITLE
Automatic layout based on height for Agenda

### ISSUE THREAD

**Issue by albsch** [nibdo/bloben-app#37]
![image](https://user-images.githubusercontent.com/38429047/170641214-2e912f0c-ff78-4916-88be-b43672f3989d.png)

In the Agenda, Day and Week views not all vertical space is used.

**Comment by nibdo** [comment]
This can be tweaked from settings/general/Hour height. Some automatic layout based on height is not yet supported, but might be in the future.

**Comment by albsch** [comment]
Ok, I'll change the title to track the automatic layout. That would be nice if it was implemented, since the web app will likely be used on many different devices.

**Comment by nibdo** [comment]
I have added some stretching to fit screen better. It is not yet perfect fit, because hour height is rounded for layout calculations, so it adds some vertical overflow, but looks better than empty space.

**Comment by albsch** [comment]
Nice! The hour height setting behaves a bit strangely now, I don't know what it does. But the automatic layout works.
