### ISSUE TITLE
Date picking NaN

### ISSUE THREAD

**Issue by albsch** [nibdo/bloben-app#38]
Creating an event and picking the time interval seems to cause some issues:

![image](https://user-images.githubusercontent.com/38429047/170669849-ae514d56-52c8-4721-9930-0fc7c3e54657.png)

**Comment by nibdo** [comment]
Can you please tell me, what browser were you using? I have added possible fix for getting system timezone,  but not sure if it was this problem as I wasn't able to replicate this.

**Comment by albsch** [comment]
Hmm, I can't reproduce it anymore. This happened with Firefox the first time I've tried to create a new event. Now, it works with all browsers I've tried and on multiple machines.

**Comment by albsch** [comment]
The issue appears consistently when I do the following:
* Try to create a new event
* Event time and date is displaying properly
* Pick another calendar
* Dates immediately turn to invalid date and I can't pick a time anymore
Affects both firefox and chromium

**Comment by nibdo** [comment]
This was probably caused by invalid timezone for particular calendar. I have added fallback to system timezone, so it should be ok now.

**Comment by albsch** [comment]
Still happens with the following versions:

Docker image version 0.8.5
Calendar version 0.7.3
Api version 0.8.3

**Comment by albsch** [comment]
It returns four events with this timezone:

```
"BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Apple Inc.//Mac OS X 10.15.1//EN\r\nCALSCALE:GREGORIAN\r\nBEGIN:VTIMEZONE\r\nTZID:Asia/Tokyo\r\nBEGIN:DAYLIGHT\r\nTZOFFSETFROM:+0900\r\nRRULE:FREQ=YEARLY;UNTIL=19510505T150000Z;BYMONTH=5;BYDAY=1SU\r\nDTSTART:19500507T000000\r\nTZNAME:GMT+9\r\nTZOFFSETTO:+1000\r\nEND:DAYLIGHT\r\nBEGIN:STANDARD\r\nTZOFFSETFROM:+1000\r\nDTSTART:19510909T010000\r\nTZNAME:GMT+9\r\nTZOFFSETTO:+0900\r\nEND:STANDARD\r\nEND:VTIMEZONE\r\nEND:VCALENDAR"
```

**Comment by nibdo** [comment]
Thank you. Hard to tell, but probably it is that "/r" fragment again. I have added fallback for invalid timezones and logger on server, so it should show exactly what timezone string was trying to use.

**Comment by albsch** [comment]
Hmm, the only thing that is printed in the combined log is this message, right after successful login:

```
{"level":"error","message":"Unknown error: {\"stack\":\"TypeError: Cannot read properties of null (reading 'identity')\\n    at /usr/app/api/src/api/userEmailConfig/handlers/getUserEmailConfig.ts:35:33\\n    at Generator.next (<anonymous>)\\n    at fulfilled (/usr/app/api/build/api/userEmailConfig/handlers/getUserEmailConfig.js:5:58)\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\",\"message\":\"Cannot read properties of null (reading 'identity')\"}","method":"GET","path":"/api/v1/users/email-config","tags":["UNKNOWN","REST"],"timestamp":"2022-06-15 08:21:56"}
```

Nothing is logged when I try to create an event, switch the calendar, and the invalid dates are shown. Version 0.9.0 | 0.8.0 | 0.9.0.

**Comment by nibdo** [comment]
You need to either update calendar at source to trigger sync change or remove and add as fresh one to see this.

**Comment by albsch** [comment]
Yes, it works after I deleted and re-added the calendar.
