### ISSUE TITLE
Wrong timezone on full-day events

### ISSUE THREAD

**Issue by SamuelBlickle** [nibdo/bloben-app#39]
Hi,

I just noticed that the selected timezone settings do not get applied correctly on full-day events.

For example a full-day event from a Baikal server with TZ Europe/Berlin on 28. May 2022 is displayed as an event from 28. May, 02:00 until 29. May 2022, 02:00 in Bloben (also set to Europe/Berlin).

It works fine with non-full-day events (e.g. like from 09:00 'til 10:00).

Could somebody kindly look into this issue?
Thank you very much!

**Comment by nibdo** [comment]
Hello, 

currently all day events should be treated as if they have "floating" timezone, so they have fixed dates regardless of the timezone. But there might be some other issue, could you please send me snippet from your original event? DTSTART and DTEND property should be enough to check this. Thank you.

**Comment by SamuelBlickle** [comment]
Seems like the events end date does indeed hold the value of the next day. However all my clients show the following event correctly as a full-day event on 19.05.2022:

`BEGIN:VEVENT
STATUS:CONFIRMED
CREATED:20220518T170517Z
UID:59bf8e28-...
DTEND;VALUE=DATE:20220520
TRANSP:OPAQUE
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
SUMMARY:Test
LAST-MODIFIED:20220518T170517Z
DTSTAMP:20220518T165046Z
DTSTART;VALUE=DATE:20220519
SEQUENCE:0
END:VEVENT`

**Comment by nibdo** [comment]
Yes, that should be like you said. I have similar event like this, which is shown correctly, so there must be something else influencing this behavior. 

Thank you, I will check and let you know.

**Comment by SamuelBlickle** [comment]
I just removed my caldav account from bloben and re-enterd it. That fixed the problem for me.
Idk if you want to keep investigating or not. If not, feel free to close this issue :)

**Comment by nibdo** [comment]
Thank you for info, I will check it if I come across it next time.

**Comment by AlexanderS** [comment]
I have the same problem. An all day event is displayed like this: 
![image](https://user-images.githubusercontent.com/149450/209833611-55ba03fd-d36e-4a87-a7a9-13dee30f2ec1.png)

This even happens when editing newly created new events:
![image](https://user-images.githubusercontent.com/149450/209833817-b7770dc1-dcf8-4806-b0c3-e0e2c688f10e.png)
