### ISSUE TITLE
single day event are displayed as a multi day event

### ISSUE THREAD

**Issue by pchampio** [nibdo/bloben-app#41]
If I have an event lasting from 22:00 to 00:30,in bloben it is displayed as an event in the "day section" on 2 days.
Other calendar don't do this if I haven't checked the event to be a "All day event". 

Example:

Correct display:
![image](https://user-images.githubusercontent.com/7476655/174486694-fa38a902-b035-4b4c-9c4f-c35dddcd83de.png)

Incorrect display:
![image](https://user-images.githubusercontent.com/7476655/174486781-39d9a4df-aa4c-4ab5-87f8-3d6f21075569.png)

This also occurs for 22:00 -> 00:00 events.

**Comment by pchampio** [comment]
ICS example
![image](https://user-images.githubusercontent.com/7476655/174487560-94a9f974-17da-4842-af37-ce605045d9dd.png)

**Comment by nibdo** [comment]
Hi, what version do you have please? Just checking because this should be fixed in latest.

**Comment by pchampio** [comment]
```
apiVersion | "0.9.0"
dockerImageVersion | "0.9.0"

```
