### ISSUE TITLE
Pre-scroll to near selected time 

### ISSUE THREAD

**Issue by albsch** [nibdo/bloben-app#42]
It would be nice when you want to change the end or start time of a event, the opened box would be at a position close to the time already present.

In the picture I wanted to set the time from 16:00 to 17:00, but the box starts at 0:00 and I have to scroll a lot to get to the desired time.  

![2022-06-21_14-39](https://user-images.githubusercontent.com/38429047/174801160-6b23055b-ed87-45c9-9abc-318d4968299c.png)

**Comment by nibdo** [comment]
It was sort of there, but broken. Fixed in new version, thank you.
