### ISSUE TITLE
Magic Link for automatic login and view selection

### ISSUE THREAD

**Issue by bam91** [nibdo/bloben-app#43]
Hey,

Is there any possiblity to provide some "magic links" which will automatic login and show a specific view? (like heimdall) Something like calendar.url/magic?token=ABC123.

Kinds
bam91

**Comment by nibdo** [comment]
Hello, for now, there is only this sort of magic link login like used in demo, which should generally work for any account:

https://demo.bloben.com/api/v1/users/login-demo?username=demo&password=Bg8v16a4q7gvC&redirect=https://demo.bloben.com/calendar?demo=true

But I would not recommend this for main accounts, as you can easily expose your credentials by accident to browser's search engine if you are not careful.

I have not yet started to work on sharing possibilities, but it is planned. This might be one way. 

Those magic links could be adjusted for permanent view, one time view, read or read/write permissions, etc.

**Comment by bam91** [comment]
Thanks for the info! This would be a nice option

**Comment by nibdo** [comment]
Related: https://github.com/nibdo/bloben-app/issues/45
