### ISSUE TITLE
[Feature] Link to Google Maps

### ISSUE THREAD

**Issue by bam91** [nibdo/bloben-app#44]
In the details of a appointment the location is showen. It would be nice to be able to click on the location and get directly to google maps. 

Links to g-maps work like this: https://developers.google.com/maps/documentation/urls/get-started#search-action .

**Comment by palitu** [comment]
Part of the drive to use this is the try and move away from google.  It would be nice to have support for Open Street Map and OsmAnd addresssing.

**Comment by nibdo** [comment]
Added in 0.14.0 with option to set provider (OSM or GM) from admin/server settings.
