### ISSUE TITLE
Admin Login details

### ISSUE THREAD

**Issue by palitu** [nibdo/bloben-app#46]
so i am installed, reverse proxied via Nginx Proxy Manager and have a subdomain all set up.

I cannot log into the Admin Login.

URL: https://calendar.mydomain.com/admin
.env: 
`INITIAL_ADMIN_PASSWORD=123`
`APP_DOMAIN=calendar.mydomain.com`

What creds do i use to log in?
Username?
Password?

**Comment by nibdo** [comment]
Hi, admin credentials are:

username: 'admin'
password: INITIAL_ADMIN_PASSWORD - in your case 123

**Comment by palitu** [comment]
that is what i thought, but it wasn't working.  I will do a fresh re-install and try again.

cheers

**Comment by palitu** [comment]
hmm.  so i deleted all DB's etc, and removed all history of the install, so it should be brand new.
![image](https://user-images.githubusercontent.com/6634784/178622974-c796cd92-8532-40b9-a41d-87c6b210c89d.png)

![image](https://user-images.githubusercontent.com/6634784/178622987-bccfbca0-1586-48b6-873b-cfc121dcce43.png)

`{"level":"warn","message":"Admin login for username admin wrong password","tags":["REST","SECURITY"],"timestamp":"2022-07-13 00:24:49"}`

I am not sure what i am doing wrong.

**Comment by nibdo** [comment]
Hello, it is hard to tell, but maybe you didn't delete migration from database so admin user was not created again.

I would give it a try with whole fresh setup or delete docker volumes for database.

**Comment by palitu** [comment]
Ok!  i have figured it out.

The sample .env file has a "comment" at the end of the line (`# you login password for admin account`)

this is all picked up as the string.  I set it to:
![image](https://user-images.githubusercontent.com/6634784/178857052-20c9c43f-1413-474c-a074-1ca37139a6fe.png)

and i could log in with user: `admin` pass: `CHANGE_ME #test`

Probably worth updating that sample env file to move the comment to another line.

**Comment by nibdo** [comment]
Oh, didn't thought about this. Thank you, I will update example
