### ISSUE TITLE
Copy event

### ISSUE THREAD

**Issue by nibdo** [nibdo/bloben-app#47]
I'll try and explain this.

For example, I have tasks that I have to repeat over a month.

Say a client books days 1, 3, 4 and 7 of the month for a task. I'll create one event on the 1st day, then copy it to days 3, 4 and 7.
We could think of a clickable "copy" option which would make a small calendar appear letting us choose the days we want.

Later in the month, same client books same task on days 15, 21, 24 and 29. I just have to copy event from 1, 3, 4 or 7 to 15, 21, 24 and 29 from the "copy" option.

Would be easier than creating another event each day a client books.

I'm not sure I explained that well, or if that's the info you need.

Let me know if I can clarify.

_Originally posted by @tiritibambix in https://github.com/nibdo/bloben-app/issues/5#issuecomment-1181147010_

**Comment by nibdo** [comment]
@tiritibambix you can check it in new version 0.12.0

**Comment by tiritibambix** [comment]
> @tiritibambix you can check it in new version 0.12.0

Wow, already ?! :D

I'm not home but I managed to try it on some computer, and I get a "Something went wrong" error ...

Not sure where to look.

**Comment by nibdo** [comment]
If you can send me error log here later, I will check it.

**Comment by tiritibambix** [comment]
Yes. As soon as I get a hand in a decent computer :)

**Comment by albsch** [comment]
Not as comfortable as `Ctrl + C` and `Ctrl + V`, but works pretty well nevertheless. Nice!

**Comment by nibdo** [comment]
Closing this for now

**Comment by tiritibambix** [comment]
> If you can send me error log here later, I will check it.

I'm still away from home and will send you logs around Aug 25th ;)
