### ISSUE TITLE
non user-specific Radicale account

### ISSUE THREAD

**Issue by palitu** [nibdo/bloben-app#49]
I am trying to add my Radicale account, as a general account (ie, just the domain, not with the calendar GUID).  Is there a way to just pass the login details?

ie:
url: radicale.domain.com
user: user 
pass: pass

then Bloben discovers all available calendars?  I belive the DAVx5 works this way.

This should also enable the creation of the new calendars too.

thanks

**Comment by nibdo** [comment]
@palitu It should work like that, but if you have any issue, please post some logs here, so we can check it.

@albsch there should be way, how to make creation work, as my baikal is ok with it. I will try to check it later.

**Comment by palitu** [comment]
ah yes.  it does work for pulling in the new calendars (really quickly too :D)

I will raise a new bug for the new calendar creation issue.
