### ISSUE TITLE
Custom date strange UI End on Date

### ISSUE THREAD

**Issue by albsch** [nibdo/bloben-app#51]
When selecting a custom end date for creating a repeating event, the UI is malformed. 

![image](https://user-images.githubusercontent.com/38429047/179351667-38afbad7-4226-4ab6-ba74-cb95a24dfa65.png)

Also for the dark theme, the theme is not applied and the pop-up calendar is not really visible.

![image](https://user-images.githubusercontent.com/38429047/179351690-9c567fa8-1bf8-4e5b-9860-f132915fbb03.png)

**Comment by nibdo** [comment]
Fixed in 0.11.1
