### ISSUE TITLE
Selecting 'All day' reduces the day by one

### ISSUE THREAD

**Issue by albsch** [nibdo/bloben-app#52]
* Click to create any `all day` event on the month view

![image](https://user-images.githubusercontent.com/38429047/179351823-b110eff2-6350-43cf-b47a-252ebf452781.png)

* Unselect `all day`

![image](https://user-images.githubusercontent.com/38429047/179351848-f76f39be-dd04-47cc-be86-e915ae050b42.png)

* Select `all day`, day is now reduced by one

![image](https://user-images.githubusercontent.com/38429047/179351861-279b1226-2a46-4391-9122-2e19122d41c7.png)

Repeat select and unselect to decrease the day by one every time. I don't think this is intended to work this way, I think the day should stay the same.

Additionally, maybe pick a time other than `0:00` as the default (when going from all day -> select time). The chance that someone wants to create an event that starts at `0:00` is quite low. 

Furthermore, maybe remember the time that was selected when you didn't intend to click `all day`, i.e. select time `13:00 - 14:00`, click `all day` by mistake, unselect `all day`, now the time is `0:00 - 0:00` again.

**Comment by nibdo** [comment]
Fixed in 0.11.1
