### ISSUE TITLE
Custom end date include last day

### ISSUE THREAD

**Issue by albsch** [nibdo/bloben-app#53]
When I pick `end repeat on date`

![image](https://user-images.githubusercontent.com/38429047/179352088-d7c3c76a-a504-4f68-aa2e-73f4ab1365fa.png)

then I expect that date to be included in the repetition. Instead, that last day is excluded:

![image](https://user-images.githubusercontent.com/38429047/179352094-40ff9ca5-34e4-47f7-88fd-aae7f9b97b76.png)

I think usability wise one should include the last day, otherwise the last day is always missed in the repetition and you have to think and select one day in advance to include that day.

**Comment by nibdo** [comment]
Fixed in 0.11.1
