### ISSUE TITLE
[BUG] multi-day event not showing on month view

### ISSUE THREAD

**Issue by palitu** [nibdo/bloben-app#56]
I have an event that goes from 2pm on one day to 1pm the following day.  It shows correctly on the week view, but not on the monthly view.  I expect to see the event across both days in month view.  

See attached.  

![image](https://user-images.githubusercontent.com/6634784/179383749-13b8c2d0-291e-4b7b-9d34-0e1aa4c683d1.png)

![image](https://user-images.githubusercontent.com/6634784/179383737-b62855de-cbd6-43b6-8aaa-822b90080f35.png)

![image](https://user-images.githubusercontent.com/6634784/179383741-79fba8cf-0c16-4a00-bea9-c2e734035139.png)

**Comment by nibdo** [comment]
Fixed in 0.11.1
