### ISSUE TITLE
Share Calendar selection gets to width

### ISSUE THREAD

**Issue by bam91** [nibdo/bloben-app#62]
When adding Calendars at sharing the names of the seleected calendars are displayed in one row. When adding to much calendars the row gets to width and the pop up is getting out of the screen on both sides. 

Possible fix: Showing all Calendars in a list, like in the selection

Aditional: A option to select all calendars would be nice. 

PS: The sharing feature is really nice! Thanks!!

**Comment by nibdo** [comment]
Hi, glad you like it :) 

I hid list of selected calendars. On second thought, it felt redundant, while they are displayed also in dropdown. Some scrollable card with list might be more informative but it didn't look pleasant.  

You will also find that select/unselect all function in latest update.
