### ISSUE TITLE
Creating 'All day' event always starts one day earlier

### ISSUE THREAD

**Issue by albsch** [nibdo/bloben-app#64]
When I create an all day event for a single day, say for 

![image](https://user-images.githubusercontent.com/38429047/185383889-0abd2be6-f361-4ef0-b9c2-a0f861d6cae9.png)

upon clicking save, I can see that the from date changes very quickly to one day earlier,
and the event is now spread onto two days:

![image](https://user-images.githubusercontent.com/38429047/185384006-a62071e0-359c-40a7-9ef9-807116c45d0a.png)

**Comment by nibdo** [comment]
Hi, can you please give me some more information as I am not able to replicate this issue? 

Are you using different timezone than your local one?

Was this always present or is it new bug?

**Comment by albsch** [comment]
The settings show that I'm currently using `Europe/Berlin` timezone, which matches my local system time zone (`CEST`).

I **think** this was introduced when #52 was fixed. But I'm not sure.

Here is a screen recording on how to reproduce it.

[out.webm](https://user-images.githubusercontent.com/38429047/185787684-fc575f48-a94d-44a0-a7b0-88784cf3f01c.webm)

The issue does not happen if I create an event anywhere **except** when I click the top bar. If I do the same procedure in any time slot, for example, it works.

**Comment by nibdo** [comment]
Thank you, I see it now.

**Comment by nibdo** [comment]
Should be fixed in new 0.14.0
