### ISSUE TITLE
Can't create new events with start and end time

### ISSUE THREAD

**Issue by drJeckyll** [nibdo/bloben-app#67]
Using:
```
Docker image version 0.15.0
Calendar version
Api version 0.15.0
```

Trying to add new event:
```
{"calendarID":"5cc2880e-0986-4f1a-a435-7beea71bee01","iCalString":"BEGIN:VCALENDAR\nPRODID:Bloben 1.0\nVERSION:2.0\nCALSCALE:GREGORIAN\nBEGIN:VEVENT\nDTSTART;TZID=floating:Invalid DateTime\nDTEND;TZID=floating:Invalid DateTime\nDTSTAMP:20220903T172624Z\nUID:33bd21e2-2100-4fb0-862a-237e96fe37e8\nCREATED:20220903T172539Z\nLAST-MODIFIED:20220903T172539Z\nSEQUENCE:0\nSTATUS:CONFIRMED\nSUMMARY:e32e32\nTRANSP:OPAQUE\nEND:VEVENT\nEND:VCALENDAR","externalID":"33bd21e2-2100-4fb0-862a-237e96fe37e8"}
```
failed with: 
```
{"code":409,"message":"Cannot create event: Unsupported Media Type"}
```

It's OK if event take whole day for example:
```
{"calendarID":"5cc2880e-0986-4f1a-a435-7beea71bee01","iCalString":"BEGIN:VCALENDAR\nPRODID:Bloben 1.0\nVERSION:2.0\nCALSCALE:GREGORIAN\nBEGIN:VEVENT\nDTSTART;VALUE=DATE:20220908\nDTEND;VALUE=DATE:20220909\nDTSTAMP:20220903T172809Z\nUID:98c4ce6f-0929-454f-939c-faa6f3869e8b\nCREATED:20220903T172539Z\nLAST-MODIFIED:20220903T172539Z\nSEQUENCE:0\nSTATUS:CONFIRMED\nSUMMARY:e32e32\nTRANSP:OPAQUE\nEND:VEVENT\nEND:VCALENDAR","externalID":"98c4ce6f-0929-454f-939c-faa6f3869e8b"}
```
result:
```
{"message":"Event created"}
```

EDIT: I see TZID=floating:Invalid DateTime
In `docker-compose.yml` I have set 
```
environment:
      TZ: 'Europe/Sofia'
```
What is correct way to set timezone?

**Comment by nibdo** [comment]
Hi, timezones are set directly from the app in settings/general.

Could you please tell me exactly from which part did you create event? (for example week view header, or week view table grid, month view)

I suspect that floating timezone is breaking date, but not sure yet, where how was it added.

**Comment by drJeckyll** [comment]
It looks like only month view is broken. I can create event from week, 3 days and day view.

But ... from week, 3days, day view if I click on 4 o clock, in popup selection is for 7 o clock (GMT+3 which is my timezone from browser I guess), even when timezone in settings/general is set to GMT+0.
In month view when I select that event is not whole day and select 07:00 from popup in edit box it say 04:00 - again 3 hours diff (timezone diff where I live).

**Comment by nibdo** [comment]
I see, thank you

**Comment by drJeckyll** [comment]
Displaying multiple day events is broken too. I have event from 15/07/2022 to 17/07/2022, but in bloben it is displayed like it is day early - from 14 to 16. I guess it is also because of timezone.

**Comment by nibdo** [comment]
Timezones should be better in next release. Currently it is in testing in staging version.

**Comment by nibdo** [comment]
Should be improved in 0.15.2
