### ISSUE TITLE
403 for all API operations

### ISSUE THREAD

**Issue by jelmer** [nibdo/bloben-app#68]
I've got bloben running in a docker container, and while I can succesfully login - all other operations against the API seem to result in a 403.

E.g. when I try to add a CalDAV account in the UI, I can see that requests against /api/app/v1/caldav-accounts are failing with a 403 and the following payload: ``{"code":403,"message":"Access forbidden"}``

What's the best way of debugging this? There's nothing useful on standard out after:

```
2022-09-06T02:16:02: PM2 log: Launching in no daemon mode
2022-09-06T02:16:02: PM2 log: App [index:0] starting in -fork mode-
2022-09-06T02:16:02: PM2 log: App [index:0] online
[NODE_ENV]:  development
Bloben Api listening at http://localhost:8081
```

**Comment by nibdo** [comment]
Hi, you have probably changed user role to DEMO in admin panel. Can you please check it? After changing role to USER, you might need to relogin.

**Comment by jelmer** [comment]
Yep, thanks! That seemed to do it (I'd actually changed it to ADMIN assuming that'd give me the same permissions as USER + some).
