### ISSUE TITLE
Handle ICS files

### ISSUE THREAD

**Issue by rhyst** [nibdo/bloben-app#70]
Hey, firstly thank you for developing bloben. It's nice to have a modern looking, self hostable calendar 🙇 

Is it possible to have bloben handle ics files? I think its possible to register a web app as a handler for certain file types. This would make it much easier to add events from emails for example.

**Comment by nibdo** [comment]
Hi, thank you :) 

I think it is still not possible to register intent in web app for calendar files like in native apps. I found workaround by connecting Bloben to email server and creating events directly from attached files in emails (either automatically or after confirmation from app).

However this feature has not been released yet.

**Comment by rhyst** [comment]
That feature would work for me 👍

**Comment by nibdo** [comment]
Added in 0.17.0

https://docs.bloben.com/docs/Emails/ImportingEventsFromEmail
