### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by aeternum1986** [nibdo/bloben-app#71]
Hi

I just installed bloben, but when I'm putting in my initial admin password, it says "unable to log in". I have tried a few different passwords, and it doesn't work. What is the user i should be using? I assumed it would be admin, so that's what I've been using, but i also tried administrator.

Docker image version 0.15.1

Calendar version

Api version 0.15.0

**Comment by aeternum1986** [comment]
I just logged into baikal with davx5, so my password is right.

**Comment by nibdo** [comment]
Hi,

for admin account, you have to use this credentials:

username: admin
password: INITIAL_ADMIN_PASSWORD - from your .env file
