### ISSUE TITLE
[Feature Request] Read-only calendars for public access

### ISSUE THREAD

**Issue by jenzopr** [nibdo/bloben-app#73]
Dear Bloben devs,

would it be possible to add read-only calendars that can be made publicly accessible? If its already possible now, please let me know :-)

Thanks for a short note!
Jens

**Comment by nibdo** [comment]
Hello,

you can either create regular user, set accounts for him and in admin panel change role to DEMO. This is how [demo](https://demo.bloben.com/api/app/v1/auth/login-demo?username=demo&password=Bg8v16a4q7gvC&redirect=https://demo.bloben.com/calendar?demo=true) calendar works.

Or you can share selected calendars from your user in settings/shared calendars. This will create public link with read only access. This way you can combine calendars from multiple accounts. 

Second option is probably best for most use cases.

**Comment by jenzopr** [comment]
Thanks! Those are two great options!
