### ISSUE TITLE
Support different timezones per event

### ISSUE THREAD

**Issue by rezzorix** [nibdo/bloben-app#88]
Any chance to add supporting definition of two different time-zones for a single event?

E.g.: flight ETD in timezone-A and ETA in timezone-B

Any CalDav-backend should support this already - therefore would be cool if the frontend client would support it, too.

**Comment by nibdo** [comment]
Hi, this is sort of partly included but disabled (because of priorities). Currently it is used only timezone from starting date.

I will check it, it would need some rewrites and testing, but I think and hope nothing big.

**Comment by nibdo** [comment]
Added in 0.16.3
