### ISSUE TITLE
Time and date issues

### ISSUE THREAD

**Issue by trentG92** [nibdo/bloben-app#94]
Bloben is using an unexpected date for 'today'. It seems to disregard the timezone used. I have tried using 'Australia/Sydney' within Bloben (settings>general) and changing the /etc/localtime symlink within the containers but it always shows what looks to be the UTC time no matter what. 
When I first login into the calendar, the Sydney timezone is selected but the calendar entries seem to reflect UTC time and I manually need to select a different timezone and reselect Sydney to have the entries shuffle to the expected timeslots for the day.
For example, right now the time in sydney is 10:47 09/11/22. 'Today' in is marked as the 8th and the current time pink bar looks to be close to midnight. My timezone is currently set Australia/Sydney

In addition to the above, when creating a new entry in the calendar, the time dropdown is propogating incorrect times. For example when I select the start date in the dropdown of '19:00', the actual time selected is 06:00. All times seem to be 11 hours different, always - regardless of timezone selected.
![image](https://user-images.githubusercontent.com/86281639/200700465-09742a63-3f9c-4039-985e-77c98abf4dbd.png)

**Comment by nibdo** [comment]
Hi, can you please check, if you still have this issues in new version 0.16.3? Thanks

**Comment by trentG92** [comment]
I have a clean set of containers running on 16.3. The time selection works now thank you! Some things I have noticed still but I will open individual issues for those.
